@startuml

title 拼团活动

Activity -left-> EnrolmentConditions : > EnrolmentConditionsId

Activity -right-> ActivityItem : >  activityId
ExamineRecord -up-> ActivityItem : > ActivityItemId

/'平台活动'/
class Activity<<Entity>>{
  - id : 主键
  - name : 活动名称
  - explain : 活动说明
  - signUpAt : 报名开始时间
  - signEndAt : 报名截止时间
  - activityUpAt : 活动开始时间
  - activityEndAt : 活动截止时间
  - sellerType : 商家类型
  - signCommodityNum : 报名商品数
  - pitsNum : 坑位数
  - freeShipping : 是否包邮
  - categoryId : 活动类目ID
  - EnrolmentConditionsId : 条件ID
  - createdAt : 创建时间
  - updatedAt : 修改时间
  - Status : 状态
}

/'报名条件'/ 
class EnrolmentConditions<<Entity>>{ 
  - id : 主键
  - name : 报名条件名称
  - requirement : 报名要求
  - createdAt : 创建时间
  - updatedAt : 修改时间
  - Status : 状态
}

/'拼团活动商品'/
class ActivityItem<<Entity>>{
  - id : 主键
  - activityId : 活动id
  - sellerAccountId : 商家id
  - itemSkuId : 商品SKUID
  - stockNum : 库存量
  - salePrice : 市场价
  - activityPrice : 拼团价
  - restrictionsNum : 限购数
  - groupNum:参团人数
  - createdAt : 创建时间
  - updatedAt : 修改时间
  - Status : 状态
}
/'审核记录表'/
class ExamineRecord<<Entity>>{
  - id : 主键
  - ActivityItemId : 审核拼团活动商品id
  - Status : 审核状态
  - rejectReson : 审核驳回原因
  - Status : 状态
}

@enduml